---
# Exercise for setting up a web server in an EC
- name: Configuration play.
  # Use the public IP if the VM is already created
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
  - setup