version: 2.1 # circle-ci API version that the config file communicates with.

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    working_directory: /tmp
    steps:
      - run: mkdir -p workspace
      - run:
          name: "Say world"
          command: echo "hello world" > /tmp/workspace/output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say world"
          command: cat /tmp/workspace/output.txt
      - attach_workspace:
          at: /tmp/workspace

workflows:
  default:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
