version: 2.1 # circle-ci API version that the config file communicates with.

jobs:
  excercise_job_failure:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1

      - run:
          name: Print Error Message
          command: echo "Hello Error!"
          when: on_fail

workflows:
  default:
    jobs:
      - excercise_job_failure
