version: 2.1 # circle-ci API version that the config file communicates with.

commands:
  print_pipeline_id:
    description: "A simple command that prints the Circle CI Workflow ID"
    parameters:
      id:
        type: string
    steps:
      - run: echo <<  parameters.id >>

jobs:
  my_command_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: <<  pipeline.id >>

workflows:
  default:
    jobs:
      - my_command_test
