version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  # create_infrastructure: 
  #       docker:
  #         - image: amazon/aws-cli
  #       steps:
  #         - checkout
  #         - run:
  #             name: Create Cloudformation Stack
  #             command: |
  #               aws cloudformation deploy \
  #                 --template-file template.yml \
  #                 --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #                 --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["25:d8:8e:51:98:ec:a8:92:bd:d5:26:32:8a:8b:fa:53"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml -i inventory

workflows:
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure 